"""first

Revision ID: c7543c8ec60f
Revises: 333a2a4759ab
Create Date: 2023-02-11 18:41:17.876212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7543c8ec60f'
down_revision = '333a2a4759ab'
branch_labels = None
depends_on = None


from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educacion', sa.Column('ed_tipo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'educacion', 'tipo_educacion', ['ed_tipo'], ['id'])
    op.add_column('experiencia', sa.Column('exp_tipo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experiencia', 'tipo_experiencia', ['exp_tipo'], ['id'])
    op.add_column('proyecto', sa.Column('proy_categoria', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proyecto', 'tipo_proyecto', ['proy_categoria'], ['id'])
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proyecto', type_='foreignkey')
    op.drop_column('proyecto', 'proy_categoria')
    op.drop_constraint(None, 'experiencia', type_='foreignkey')
    op.drop_column('experiencia', 'exp_tipo')
    op.drop_constraint(None, 'educacion', type_='foreignkey')
    op.drop_column('educacion', 'ed_tipo')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
